ilabpro01_front_homepage:
    pattern:  /hello
    defaults: { _controller: ilabpro01FrontBundle:Front:loginFront }


front_homepage:
    pattern:  /front
    defaults: { _controller: ilabpro01FrontBundle:Front:index }
    
    
url_fotog:
    pattern:  /urlf
    defaults: { _controller: ilabpro01FrontBundle:Front:urlFotog }       

   
show_fotog:
    pattern:  /showf
    defaults: { _controller: ilabpro01FrontBundle:Front:showFotog }    
    
    
mostrar_eventos:
    pattern:  /showevent
    defaults: { _controller: ilabpro01FrontBundle:Front:showEventos }     


acceso_eventos:
    pattern:  /accesoevent
    defaults: { _controller: ilabpro01FrontBundle:Front:accesoEventos }  
    
    