parameters:
#    ilabpro01_front.example.class: ilabpro01\FrontBundle\Example

services:
#    ilabpro01_front.example:
#        class: %ilabpro01_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
