ilabpro01_back_fotog_homepage:
    pattern:  /hello
    defaults: { _controller: ilabpro01BackFotogBundle:Back:index }
    
    
albumes:
    pattern:  /albumes
    defaults: { _controller: ilabpro01BackFotogBundle:albumes:index }
    
    
albumes_create:
    pattern:  /albumes
    defaults: { _controller: ilabpro01BackFotogBundle:albumes:create }
    
    
albumes_new:
    pattern:  /albumes/new
    defaults: { _controller: ilabpro01BackFotogBundle:albumes:new }
    
    
albumes_show:
    pattern:  /albumes/{id}
    defaults: { _controller: ilabpro01BackFotogBundle:albumes:show }
    
    
albumes_edit:
    pattern:  /albumes/{id}/edit
    defaults: { _controller: ilabpro01BackFotogBundle:albumes:edit }
    
    
albumes_update:
    pattern:  /albumes/{id}
    defaults: { _controller: ilabpro01BackFotogBundle:albumes:update }
    
    
albumes_delete:
    pattern:  /albumes/{id}
    defaults: { _controller: ilabpro01BackFotogBundle:albumes:delete }   
 
    
fotog_edit:
    pattern:  /fotografo/{id}/edit
    defaults: { _controller: ilabpro01BackFotogBundle:Back:fotogEdit }

  
fotog_imagen:
    pattern:  /fotografo/imagen
    defaults: { _controller: ilabpro01BackFotogBundle:Back:fotogImagen }
    
    
index_back:
    pattern:  /hello
    defaults: { _controller: ilabpro01BackFotogBundle:Back:index }

    
lista_eventos:
    pattern:  /listaeventos
    defaults: { _controller: ilabpro01BackFotogBundle:Back:listadoEventos }
    
    
lista_fotog_pedidos:
    pattern:  /listap
    defaults: { _controller: ilabpro01BackFotogBundle:Back:listadoPedidos }
    
   
lista_productos:
    pattern:  /listaprod
    defaults: { _controller: ilabpro01BackFotogBundle:Back:listadoProductos }
    
    
lista_usuarios:
    pattern:  /listausuarios
    defaults: { _controller: ilabpro01BackFotogBundle:Back:listadoUsuarios }
    
    
login_fotog:
    pattern:  /login
    defaults: { _controller: ilabpro01BackFotogBundle:Back:login }
    
    
pedidos:
    pattern:  /pedidos
    defaults: { _controller: ilabpro01BackFotogBundle:Back:pedidos }
  
  
pendientes:
    pattern:  /pendientes
    defaults: { _controller: ilabpro01BackFotogBundle:Back:listadoPendientes }
    
    
perfil_fotog:
    pattern:  /perfil
    defaults: { _controller: ilabpro01BackFotogBundle:Back:perfil }
    
    
plan_fot:
    pattern:  /planfot
    defaults: { _controller: ilabpro01BackFotogBundle:Back:seleccionarPlan }
    
    
precios_productos:
    pattern:  /preciosprod
    defaults: { _controller: ilabpro01BackFotogBundle:Back:preciosProductos }
    


    

    


