parameters:
#    ilabpro01_general.example.class: ilabpro01\GeneralBundle\Example

services:
#    ilabpro01_general.example:
#        class: %ilabpro01_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
